DurabilityNotify Configuration:
  Main:
    Give OPs all permissions: true
  Tools:
    Pickaxe:
      Wooden: [1, 10]
      Stone: [1, 10]
      Iron: [1, 10]
      Gold: [1, 10]
      Diamond: [1, 50, 200, 500]
    Shovel:
      Wooden: [1, 10]
      Stone: [1, 10]
      Iron: [1, 10]
      Gold: [1, 10]
      Diamond: [1, 50, 200, 500]
    Axe:
      Wooden: [1, 10]
      Stone: [1, 10]
      Iron: [1, 10]
      Gold: [1, 10]
      Diamond: [1, 50, 200, 500]
    Sword:
      Wooden: [1, 10]
      Stone: [1, 10]
      Iron: [1, 10]
      Gold: [1, 10]
      Diamond: [1, 50, 200, 500]
    Hoe:
      Wooden: [1, 10]
      Stone: [1, 10]
      Iron: [1, 10]
      Gold: [1, 10]
      Diamond: [1, 50, 200, 500]
    Bow: [1, 10]
    Fishing Rod: [1, 10]
    Flint and Steel: [1, 10]
    Shears: [1, 10]
    Carrot Stick: [1, 10]
  Armor:
    Leather:
      Helmet: [0, 5]
      Chestplate: [0, 5]
      Leggings: [0, 5]
      Boots: [0, 5]
    Gold:
      Helmet: [0, 5]
      Chestplate: [0, 5]
      Leggings: [0, 5]
      Boots: [0, 5]
    Chainmail:
      Helmet: [0, 5]
      Chestplate: [0, 5]
      Leggings: [0, 5]
      Boots: [0, 5]
    Iron:
      Helmet: [0, 5]
      Chestplate: [0, 5]
      Leggings: [0, 5]
      Boots: [0, 5]
    Diamond:
      Helmet: [0, 5]
      Chestplate: [0, 5]
      Leggings: [0, 5]
      Boots: [0, 5]
  Timed Reminders:
    Enabled: false
    Minutes: 30
  Messages:
    Live Durability on: "&2[Live durability notifications on]"
    Live Durability off: "&4[Live durability notifications off]"
    ToolWarning: "&4[&eWarning&4] &eYour %COLOR%%ITEM% &e%GRAMMAR% &7%USES% &e%GRAMMAR2% left"
    ToolWarningBroken: "&4[&eWarning&4] &eYour %COLOR%%ITEM% &e%GRAMMAR% broken"
    ArmorWarning: "&4[&eWarning&4] &eYour %COLOR%%ITEM% &e%GRAMMAR% &7%PERCENT%% &edurability remaining"
    ArmorWarningBroken: "&4[&eWarning&4] &eYour %COLOR%%ITEM% &e%GRAMMAR% broken"
    Info: "&f[&aInfo&f] &aYour %COLOR%%ITEM% &a%GRAMMAR% &f%USES% &auses left"
    InfoBroken: "&f[&aInfo&f] &aYour %COLOR%%ITEM% &e%GRAMMAR% broken"
    Reminder: "&f[&aReminder&f] &eYour %COLOR%%ITEM% &e%GRAMMAR% less than %COLOR%%PERCENT% &edurability remaining"
    Improper Tool Message: "&4[&eWarning&4]&e You are also using the wrong tool"
    Grammar Singular: "has"
    Grammar Plural: "have"
    Grammar2 Singular: "use"
    Grammar2 Plural: "uses"
