name: DurabilityNotify
main: co.proxa.durabilitynotify.DurabilityNotify
author: proxa
version: 0.7
description: Reminds players when their tools and/or armor are at low durability

commands:
   dura:
     description: Toggle live durability notifications
     permission-message: Sorry, you don't have permission
   armor:
     description: Shows current armor durability
     permission-message: Sorry, you don't have permission
   arm:
     description: Shorthand version of armor command
     permission-message: Sorry, you don't have permission

permissions:
   dura.tools:
     description: Notifies player of low tool durability
   dura.armor:
     description: Notifies player of low armor durability
