name: DurabilityNotify
main: org.hopto.seed419.DurabilityNotify
author: seed419
version: 0.1
description: Reminds players when their tools are at low durability

commands:
   dura:
     description: Toggle live durability notifications
     permission-message: Sorry, you dont have permission

permissions:
   dura.tools:
     description: Notifies player of low tool durability
   dura.armor:
     description: Notifies player of low armor durability