name: DurabilityReminder
main: org.hopto.seed419.DurabilityReminder
author: seed419
version: 0.0.4
description: Reminds players when their tools are at low durability

permissions:
    durability.notify:
        description: Notifies player of low tool durability